version: '3'

services:
  phpmyadm:
    image: phpmyadmin/phpmyadmin
    ports:
      - "9000:80"
    environment:
      - PMA_ARBITRARY=1
      - "PMA_HOST=mysqldb"
    restart: always
    depends_on:
      - mysqldb
  
  mysqldb:
    platform: linux/x86_64
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - 'MYSQL_ROOT_PASSWORD=root'
      - 'MYSQL_USER=dev'
      - 'MYSQL_PASSWOR=dev'
    volumes:
      - "./mysql/data:/var/lib/mysql"
    restart: always